# Generated by Django 5.1.15 on 2026-09-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BlogSaaS', max_length=100)),
                ('site_description', models.CharField(default='Modern blog publishing SaaS platform for writers, developers, and creators.', max_length=255)),
                ('hero_headline', models.CharField(default='Publishing reimagined for modern creators.', max_length=200)),
                ('hero_subheadline', models.TextField(default='Create, curate, and grow your audience with an ultra-fast editorial reading experience.')),
                ('allow_user_registration', models.BooleanField(default=True)),
                ('require_approval_for_blogs', models.BooleanField(default=True, help_text='Require admin approval before user blogs are published.')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(default='support@blogsaas.com', max_length=254)),
                ('footer_text', models.TextField(default='© 2026 BlogSaaS Inc. All rights reserved.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Describe why this content violates community guidelines', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.blog')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
