# Generated by Django 5.1.15 on 2026-09-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_report_comment_alter_report_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='sanskarkumar871@gamil.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(default='© 2026 Blogs Monkey Inc. All rights reserved.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subheadline',
            field=models.TextField(default='Create, curate, and grow your audience with Blogs Monkey editorial experience.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Blogs Monkey', max_length=100),
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('approx_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('status', models.CharField(db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Record',
                'verbose_name_plural': 'AI Usage Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
